name:                h101
version:             0.1.0.0
description:         First steps with Haskell
license:             BSD3
author:              Nick Chapman
maintainer:          nic@amadido.co.uk
github:              Nick-Chapman/mentoring.git/h101

extra-source-files:
- README.md

dependencies:
- array
- base >= 4.7 && < 5
- bytestring
- clock
- containers
- data-ordlist
- mtl
- process
- unix

default-extensions:
- BangPatterns
- DuplicateRecordFields
- EmptyDataDeriving
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- NamedFieldPuns
- NondecreasingIndentation
- NumericUnderscores
- ScopedTypeVariables
- ImportQualifiedPost

ghc-options:
- -Werror
- -Wall
- -Wno-name-shadowing
- -O2

library:
  source-dirs: src

executables:
  main.exe:
    main:                app/main.hs
    dependencies:        h101
