name:                h101
version:             0.1.0.0
description:         First steps with Haskell
license:             BSD3
author:              Nick Chapman
maintainer:          nic@amadido.co.uk
github:              Nick-Chapman/mentoring.git/h101

extra-source-files:
- README.md

dependencies:
- ansi-terminal
- array
- async
- base >= 4.7 && < 5
- bytestring
- clock
- containers
- data-ordlist
- extra
- haskeline
- mtl
- split
- text
- time
- transformers
- word8
#- EarleyM

default-extensions:
- BangPatterns
- DuplicateRecordFields
- EmptyCase
- EmptyDataDeriving
- FlexibleContexts
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- MultiWayIf
- NamedFieldPuns
- NondecreasingIndentation
- NumericUnderscores
- RankNTypes
- RecursiveDo
- ScopedTypeVariables
- TypeApplications
- TypeFamilies
- UndecidableInstances

ghc-options:
- -Werror
- -Wall
- -Wno-name-shadowing
- -O2

library:
  source-dirs: src

executables:
  main.exe:
    main:                app/main.hs
    dependencies:        h101
